"""Agregar tabla habitacion

Revision ID: 26c22975473a
Revises: d3a626b4e5e7
Create Date: 2025-11-23 12:37:28.958349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26c22975473a'
down_revision = 'd3a626b4e5e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habitacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nro_habitacion', sa.String(length=10), nullable=False),
    sa.Column('tipo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tipo_id'], ['tipo_habitacion.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nro_habitacion')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('habitacion')
    # ### end Alembic commands ###
