"""Agregar tabla estadia

Revision ID: 6c2022579b09
Revises: 26c22975473a
Create Date: 2025-11-23 20:01:41.307724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c2022579b09'
down_revision = '26c22975473a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estadia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_ingreso', sa.Date(), nullable=False),
    sa.Column('fecha_egreso', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('precio_total', sa.Float(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('tipo_habitacion_id', sa.Integer(), nullable=False),
    sa.Column('habitacion_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['habitacion_id'], ['habitacion.id'], ),
    sa.ForeignKeyConstraint(['persona_id'], ['persona.id'], ),
    sa.ForeignKeyConstraint(['tipo_habitacion_id'], ['tipo_habitacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('estadia')
    # ### end Alembic commands ###
