"""Agregar tablas servicio y consumo

Revision ID: 6df7a5143298
Revises: f12e4d780043
Create Date: 2025-11-24 15:45:25.848108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6df7a5143298'
down_revision = 'f12e4d780043'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consumo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estadia_id', sa.Integer(), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('fecha_consumo', sa.Date(), nullable=True),
    sa.Column('precio_unitario_historico', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['estadia_id'], ['estadia.id'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consumo')
    op.drop_table('servicio')
    # ### end Alembic commands ###
