"""Agregar imagen y actualizar precio

Revision ID: 889a56b5da0e
Revises: 
Create Date: 2025-11-22 15:05:09.918127

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '889a56b5da0e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('habitacion')
    op.drop_table('tipo_habitacion')
    op.drop_table('servicio')
    op.drop_table('tipohabitacion')
    op.drop_table('estadia')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estadia',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fecha_ingreso', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('fecha_egreso', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('estado', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('precio_total', sa.REAL(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='estadia_pkey')
    )
    op.create_table('tipohabitacion',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('denominacion', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('descripcion', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('foto', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('capacidad_personas', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('precio_por_dia', sa.REAL(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='tipohabitacion_pkey')
    )
    op.create_table('servicio',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('descripcion', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('precio', sa.REAL(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='servicio_pkey')
    )
    op.create_table('tipo_habitacion',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('tipo_habitacion_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('denominacion', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('foto', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('capacidad_personas', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('precio_por_dia', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='tipo_habitacion_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('habitacion',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nro_habitacion', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('tipo_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tipo_id'], ['tipo_habitacion.id'], name='habitacion_tipo_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='habitacion_pkey'),
    sa.UniqueConstraint('nro_habitacion', name='habitacion_nro_habitacion_key')
    )
    # ### end Alembic commands ###
