"""Actualizar tabla tipo_habitacion con imagenes

Revision ID: d3a626b4e5e7
Revises: 889a56b5da0e
Create Date: 2025-11-22 15:25:57.021381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3a626b4e5e7'
down_revision = '889a56b5da0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo_habitacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('denominacion', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('capacidad_personas', sa.Integer(), nullable=False),
    sa.Column('precio_por_noche', sa.Float(), nullable=False),
    sa.Column('nombre_imagen', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tipo_habitacion')
    # ### end Alembic commands ###
