"""Agregar campo cantidad_personas a estadia

Revision ID: f12e4d780043
Revises: 6c2022579b09
Create Date: 2025-11-24 11:16:18.209032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f12e4d780043'
down_revision = '6c2022579b09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estadia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cantidad_personas', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estadia', schema=None) as batch_op:
        batch_op.drop_column('cantidad_personas')

    # ### end Alembic commands ###
